services:
  frontend:
    build:
      context: ./project/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./project/frontend:/app/frontend
      - /app/frontend/node_modules
    entrypoint: npm run dev -- --host 0.0.0.0 --port 3000
